In [8]:
import tfx.v1 as tfx
import tensorflow as tf
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [18]:
Number = np.random.randint(1,150,size=[10,10])
print(f"{Number}\n{type(Number)}")

[[ 92   9  59 110 149 105  98  76 146 116]
 [ 16  75  77 100 111  22 105  75  74 138]
 [134  71  20 103 122  60  10   4  78 136]
 [ 23 107  67   6  44  33  68  56  27 124]
 [ 15  93 107  66  29  33 144 103  82 120]
 [ 12 120 106  21  94 119 123   3  12 113]
 [ 18  65 138  75  93  15  79  75 134 126]
 [ 71 118 143   8 112  72  99  79 128  98]
 [ 23 129 138 128 120 103 122 111  90 110]
 [114  79  41 119 119  76  36 138  78 124]]
<class 'numpy.ndarray'>


In [19]:
angka_2 = tf.ones([10,10],)
print(f"{angka_2}\n{type(angka_2)}")

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [36]:
Tensor_Number = tf.multiply(angka_2,np.random.randint(1,10))
print(f"{Tensor_Number}\n{type(Tensor_Number)}")

[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [37]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])

print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [51]:
Rank = tf.constant([[1,2,3],
                    [1,3,5],
                    [4,6,6]])
Rank

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 3, 5],
       [4, 6, 6]])>

In [52]:
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
